export type BankLayoutType = "centered" | "split-left" | "split-right" | "full-width";

export type BlockType = "header" | "form" | "footer" | "spacer";

export type BankElement = {
  id: string;
  type: "container" | "text" | "input" | "button" | "image" | "form";
  content?: string; 
  attributes?: Record<string, string>;
  styles: Record<string, string>;
  children?: BankElement[];
};

export type BankDesignConfig = {
  layout: BankLayoutType;
  blocks: BlockType[]; // For drag and drop ordering
  background: {
    type: "color" | "image";
    value: string; // HEX color or Image URL
  };
  header: {
    show: boolean;
    backgroundColor: string;
    height: string; // e.g., "80px", "100px"
    logoAlignment: "left" | "center" | "right";
    padding: string;
  };
  formBox: {
    backgroundColor: string;
    textColor: string;
    borderRadius: string; // e.g., "0px", "8px", "16px"
    boxShadow: string; // none, sm, md, lg
    padding: string; // e.g., "24px"
    width: string; // e.g., "400px", "100%"
    alignment: "left" | "center" | "right";
  };
  button: {
    backgroundColor: string;
    hoverColor: string;
    textColor: string;
    borderRadius: string;
    padding: string;
    fontWeight: string;
  };
  typography: {
    fontFamily: string; // e.g., "sans-serif", "serif"
    headerColor: string;
    bodyColor: string;
    linkColor: string;
  };
  texts: {
    title: string;
    subtitle: string;
    footerLinks: string[]; // e.g., ["Contact", "Privacy", "Veilig bankieren"]  
  };
  customCss?: string; // For any fine-tuning
  customHtml?: string; // Pure HTML/Tailwind template generated by AI for perfect pixel-to-pixel custom components
  visualTree?: BankElement; // Fully editable visual DOM tree
};

export const DEFAULT_DESIGN_CONFIG: BankDesignConfig = {
  layout: "centered",
  blocks: ["header", "spacer", "form", "spacer", "footer"],
  background: { type: "color", value: "#f4f4f5" },
  header: {
    show: true,
    backgroundColor: "#ffffff",
    height: "80px",
    logoAlignment: "left",
    padding: "0 2rem",
  },
  formBox: {
    backgroundColor: "#ffffff",
    textColor: "#333333",
    borderRadius: "8px",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
    padding: "2rem",
    width: "400px",
    alignment: "center",
  },
  button: {
    backgroundColor: "#0051a5",
    hoverColor: "#003d7a",
    textColor: "#ffffff",
    borderRadius: "4px",
    padding: "0.75rem 1.5rem",
    fontWeight: "600",
  },
  typography: {
    fontFamily: "system-ui, sans-serif",
    headerColor: "#111827",
    bodyColor: "#4b5563",
    linkColor: "#0051a5",
  },
  texts: {
    title: "Inloggen",
    subtitle: "Log in met je toegangsnaam en wachtwoord.",
    footerLinks: ["Contact", "Veilig bankieren", "Privacy"],
  },
};
